"""make city nullable

Revision ID: 696d7c983d0e
Revises: 1c6e103108a0
Create Date: 2025-04-10 22:32:56.173423

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "696d7c983d0e"
down_revision: str | None = "1c6e103108a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "city", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "city", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###
