"""wip

Revision ID: 41a4eccae865
Revises: 696d7c983d0e
Create Date: 2025-04-19 23:59:17.379280

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41a4eccae865"
down_revision: str | None = "696d7c983d0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_location_interactions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("interaction_type", sa.Enum("LIKE", "HIDE", "FAVORITE", name="interactiontype"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("locations", sa.Column("categories", sa.JSON(), nullable=True))
    op.add_column("locations", sa.Column("maps_url", sa.String(length=255), nullable=True))
    op.drop_column("locations", "category")
    op.add_column("photos", sa.Column("order", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("photos", "order")
    op.add_column("locations", sa.Column("category", sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column("locations", "maps_url")
    op.drop_column("locations", "categories")
    op.drop_table("user_location_interactions")
    # ### end Alembic commands ###
